project:
  type: website

website:
  title: "myRProject2"
  navbar:
    left:
      - href: inst/qmd/main_1.qmd
        text: Home
      - inst/qmd/about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
