project:
  type: website

website:
  title: "myRProject2"
  navbar:
    left:
      - href: inst/qmd/main_1.qmd
        text: Home
      - href: inst/qmd/duckdb_csv.zip_url.qmd
        text: duckdb_csv.zip_url
      - href: inst/qmd/about.qmd
        text: Notes

format:
  # html:
  #   theme: cosmo
  #   css: styles.css
  #   toc: true
  dashboard:
    orientation: columns
    theme: cosmo
    nav-buttons: [github, twitter]

page-layout: custom
toc: true

execute:
  echo: true
